@extends('layouts.app')
@section('title', 'Reportes SCM | ECore Agents')
@section('body-class', 'admin-page')
@section('content')
<section class="admin-hero"><span class="section-eyebrow">Etapa 2 · SCM</span><h1>Reportes SCM</h1><p>Indicadores calculados con los productos, movimientos y pedidos registrados.</p></section>
<section class="admin-layout">@include('scm._sidebar')<div class="admin-content dashboard-content">
<div class="admin-summary-grid crm-summary-grid"><article class="admin-summary-card"><span>Recursos IA</span><strong>{{ $totales['productos'] }}</strong></article><article class="admin-summary-card"><span>Proveedores</span><strong>{{ $totales['proveedores'] }}</strong></article><article class="admin-summary-card"><span>Pedidos pendientes</span><strong>{{ $totales['pedidos_pendientes'] }}</strong></article><article class="admin-summary-card"><span>Stock bajo</span><strong>{{ $totales['inventario_critico'] }}</strong></article></div>

<div class="reports-grid">
<section class="dashboard-panel"><div class="admin-section-heading"><div><span class="section-eyebrow">Últimos 30 días</span><h2>Top 5 recursos más consumidos</h2></div></div>
<div class="report-bar-chart">@forelse($masConsumidos as $producto)<div class="report-bar-row"><div><strong>{{ $producto->nombre }}</strong><span>{{ (int) ($producto->consumo_30_dias ?? 0) }} unidades</span></div><div class="report-bar-track" role="img" aria-label="{{ $producto->nombre }}: {{ (int) ($producto->consumo_30_dias ?? 0) }} unidades"><span class="report-bar-fill" style="width: {{ round(((int) ($producto->consumo_30_dias ?? 0) / $maxConsumo) * 100) }}%"></span></div></div>@empty<p>Sin recursos registrados.</p>@endforelse</div></section>

<section class="dashboard-panel"><div class="admin-section-heading"><div><span class="section-eyebrow">Últimos 30 días</span><h2>Rotación de recursos</h2></div></div>
<div class="rotation-layout"><div class="rotation-donut" style="--alta: {{ $rotacion['total'] ? ($rotacion['alta'] / $rotacion['total']) * 100 : 0 }}%; --media: {{ $rotacion['total'] ? (($rotacion['alta'] + $rotacion['media']) / $rotacion['total']) * 100 : 0 }}%" role="img" aria-label="Rotación alta {{ $rotacion['alta'] }}, media {{ $rotacion['media'] }}, baja {{ $rotacion['baja'] }}"><span><strong>{{ $rotacion['porcentaje_movimiento'] }}%</strong>con movimiento</span></div><ul class="report-legend"><li class="is-high">Alta <strong>{{ $rotacion['alta'] }}</strong></li><li class="is-medium">Media <strong>{{ $rotacion['media'] }}</strong></li><li class="is-low">Baja <strong>{{ $rotacion['baja'] }}</strong></li></ul></div></section>

<section class="dashboard-panel"><div class="admin-section-heading"><h2>Inventario crítico</h2></div><div class="table-wrap"><table><thead><tr><th>Recurso</th><th>Proveedor</th><th>Stock</th><th>Mínimo</th><th>Diferencia</th></tr></thead><tbody>@forelse($criticos as $producto)<tr><td>{{ $producto->nombre }}</td><td>{{ $producto->proveedor->nombre }}</td><td>{{ $producto->stock_actual }}</td><td>{{ $producto->stock_minimo }}</td><td>{{ $producto->stock_actual - $producto->stock_minimo }}</td></tr>@empty<tr><td colspan="5">No hay recursos en nivel crítico.</td></tr>@endforelse</tbody></table></div></section>

<section class="dashboard-panel"><div class="admin-section-heading"><div><span class="section-eyebrow">Últimos 6 meses</span><h2>Consumo mensual por estrategia actual</h2></div></div><p class="report-note">Los movimientos se agrupan según la estrategia que tiene actualmente cada producto.</p><div class="monthly-chart" role="img" aria-label="Consumo mensual PUSH y PULL de los últimos seis meses">@foreach($consumoMensual['meses'] as $mes)<div class="monthly-group"><div class="monthly-bars"><span class="monthly-bar is-push" style="height: {{ round(($mes['push'] / $consumoMensual['maximo']) * 100) }}%" title="PUSH: {{ $mes['push'] }}"><b>{{ $mes['push'] }}</b></span><span class="monthly-bar is-pull" style="height: {{ round(($mes['pull'] / $consumoMensual['maximo']) * 100) }}%" title="PULL: {{ $mes['pull'] }}"><b>{{ $mes['pull'] }}</b></span></div><strong>{{ $mes['etiqueta'] }}</strong></div>@endforeach</div><ul class="monthly-legend"><li><span class="is-push"></span>PUSH</li><li><span class="is-pull"></span>PULL</li></ul></section>
</div></div></section>
@endsection
