<?php

return [
    'plans' => [
        'inicio' => [
            'slug' => 'inicio',
            'name' => 'Agente Inicio',
            'eyebrow' => 'Atención esencial',
            'catalog_eyebrow' => 'Para comenzar',
            'badge' => 'Básico',
            'tier' => 'start',
            'category' => 'basic',
            'price' => 499,
            'summary' => 'Ideal para negocios que quieren responder dudas frecuentes y mostrar información básica por WhatsApp.',
            'inheritance' => null,
            'ideal_for' => 'Negocios pequeños con bajo volumen de mensajes que desean ofrecer respuestas rápidas y consistentes sin complicar su operación.',
            'ideal_number' => '01',
            'features' => [
                'Responde mensajes con IA',
                'Catálogo básico de productos o servicios',
                'Preguntas frecuentes',
                'Horarios e información del negocio',
                'Personalización básica del agente',
                'Historial conversacional básico',
                'Escalamiento manual a humano',
            ],
        ],
        'plus' => [
            'slug' => 'plus',
            'name' => 'Agente Plus',
            'eyebrow' => 'Seguimiento inteligente',
            'catalog_eyebrow' => 'Para dar seguimiento',
            'badge' => 'Popular',
            'tier' => 'plus',
            'category' => 'follow-up',
            'price' => 999,
            'summary' => 'Ideal para negocios que reciben más mensajes y necesitan organizar clientes, audios y seguimientos.',
            'inheritance' => 'Incluye todo lo de Agente Inicio y suma herramientas para comprender mejor a cada cliente y mantener conversaciones activas.',
            'ideal_for' => 'Negocios con mensajes frecuentes que necesitan organizar prospectos, responder audios y dar seguimiento sin perder oportunidades.',
            'ideal_number' => '02',
            'features' => [
                'Transcripción de audios recibidos',
                'Respuestas más personalizadas según el contexto',
                'Catálogo avanzado de productos o servicios',
                'Clasificación de clientes: interesado, duda, compra o soporte',
                'Recordatorios automáticos por WhatsApp',
                'Seguimiento de conversaciones inconclusas',
                'Etiquetas para organizar clientes',
                'Sugerencias de mejora para el contexto del agente',
                'Historial conversacional extendido',
                'Reporte básico de actividad',
            ],
        ],
        'avanzado' => [
            'slug' => 'avanzado',
            'name' => 'Agente Avanzado',
            'eyebrow' => 'Automatización completa',
            'catalog_eyebrow' => 'Para automatizar',
            'badge' => 'Completo',
            'tier' => 'advanced',
            'category' => 'advanced',
            'price' => 1799,
            'promotional_price' => 1619.10,
            'promotion_code' => 'AVANZADO10',
            'summary' => 'Ideal para negocios que quieren automatizar atención, citas, seguimiento y reportes desde WhatsApp.',
            'inheritance' => 'Incluye todo lo de Agente Plus y agrega automatización avanzada para tomar acción, priorizar clientes y detectar oportunidades.',
            'ideal_for' => 'Negocios con alto volumen de mensajes y citas que buscan automatizar su operación y tomar decisiones con información clara.',
            'ideal_number' => '03',
            'features' => [
                'Generación de respuestas en audio',
                'Agenda de citas por WhatsApp',
                'Confirmación y recordatorios de citas',
                'Reportes avanzados de conversaciones',
                'Alertas importantes al dueño',
                'Autoaprendizaje supervisado',
                'Sugerencias automáticas para mejorar productos, respuestas o contexto',
                'Historial conversacional avanzado',
                'Flujos personalizados por tipo de cliente',
                'Detección de intención: compra, soporte, queja o cotización',
                'Prioridad de atención',
                'Llamadas por WhatsApp como función avanzada/futura',
            ],
        ],
    ],
    'modules' => [
        'plus' => [
            ['name' => 'Transcripción de audios', 'price' => 75],
            ['name' => 'Recordatorios por WhatsApp', 'price' => 75],
            ['name' => 'Seguimiento de conversaciones inconclusas', 'price' => 75],
            ['name' => 'Clasificación de clientes', 'price' => 75],
            ['name' => 'Etiquetas para organizar clientes', 'price' => 50],
            ['name' => 'Historial conversacional extendido', 'price' => 50],
            ['name' => 'Reporte básico de actividad', 'price' => 50],
            ['name' => 'Sugerencias de mejora del contexto', 'price' => 50],
        ],
        'advanced' => [
            ['name' => 'Agenda de citas', 'price' => 200],
            ['name' => 'Confirmación de citas', 'price' => 150],
            ['name' => 'Respuestas en audio', 'price' => 150],
            ['name' => 'Alertas avanzadas al dueño', 'price' => 150],
            ['name' => 'Reportes avanzados', 'price' => 150],
            ['name' => 'Autoaprendizaje supervisado', 'price' => 200],
            ['name' => 'Flujos personalizados', 'price' => 200],
            ['name' => 'Llamadas por WhatsApp', 'price' => 100],
        ],
    ],
];
